print("Question1")
from tkinter import *
root = Tk()
hL = Label(root, text='Hello World!')
hL.pack()
eB = Button(root, text='Exit', command=root.destroy)
eB.pack()
root.mainloop()
print('*'*10)
print('\n')

print("Question2")
from tkinter import *
root = Tk()
hL = Label(root, text='Hello World!')
hL.pack()
def messageA():
   lbL = Label(root, text='Have a nice day!!')
   lbL.pack()
aB = Button(root, text='Action', command=messageA)
aB.pack()
eB = Button(root, text='Exit', command=root.destroy)
eB.pack()
root.mainloop()
print('*'*10)
print('\n')

print("Question3")
from tkinter import *
root = Tk()
frame_1 = Frame(root, bg='pink')
frame_1.pack(fill=X)
def messageA():
  lbL1.configure(text='Have a nice day!!')
lbL1 = Label(frame_1, text='Good day', bg='pink')
lbL1.pack()
aB = Button(root, text='Action', bg='red', command=messageA)
aB.pack()
eB = Button(root, text='Exit', bg='purple', command=root.destroy)
eB.pack()
root.mainloop()
print('*'*10)
print('\n')

print("Question4")
from tkinter import *
root = Tk()
def show_entry():
    lbL3 = Label(root, text=e1.get())
    lbL3.grid(row=4, column=0)
    lbL4 = Label(root, text=e2.get())
    lbL4.grid(row=4, column=1)
lbL1 = Label(root, text='First Name')
lbL1.grid(row=0, column=0)
lbL2 = Label(root, text='Last Name')
lbL2.grid(row=1, column=0)
e1 = Entry(root)
e2 = Entry(root)
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
aB = Button(root, text='Show', command=show_entry)
aB.grid(row=3, column=1)
eB = Button(root, text='Exit', command=root.destroy)
eB.grid(row=2, column=1)
root.mainloop()

